# -*- coding: utf-8 -*-
"""Titanic DD

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J0a1TJFi-OSXkAd1er6pDjVlawdiwB2O
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

dataset=pd.read_csv("/content/drive/MyDrive/Titanic-Dataset).csv")
print(dataset.head())

plt.figure(figsize=(10,8))
sns.heatmap(dataset.corr(numeric_only=True),annot=True,cmap='YlGnBu')
plt.title("Correlation Heatmap")
plt.show()

dataset.hist(figsize=(12,10))
plt.show()

numeric_dataset=dataset.select_dtypes(include=[np.number])
Q1=numeric_dataset.quantile(0.25)
Q3=numeric_dataset.quantile(0.75)
IQR=Q3-Q1

dataset=dataset[~((numeric_dataset < (Q1-1.5*IQR))|(numeric_dataset>(Q3+1.5*IQR))).any(axis=1)]
print("Dataset shape after removing outliers:",dataset.shape)

plt.figure(figsize=(12,6))
dataset.boxplot()
plt.xticks(rotation=90)
plt.title("Outlier Detection")
plt.show()

x=dataset[["Pclass","Age"]].dropna()
y=dataset.loc[x.index,"Survived"]
plt.scatter(x["Pclass"],x["Age"],c=y)
plt.xlabel("Passenger class")
plt.ylabel("Age")
plt.title("Feature Visulaization")
plt.show()

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=0)

from sklearn.tree import DecisionTreeClassifier
model=DecisionTreeClassifier(criterion='entropy',random_state=0)
model.fit(x_train,y_train)

y_pred=model.predict(x_test)
print("predictions:",y_pred)

from sklearn.metrics import confusion_matrix, accuracy_score
cm=confusion_matrix(y_test,y_pred)
print("Confusion Matrix:")
print(cm)
accuracy=accuracy_score(y_test,y_pred)
print("Accuracy:",accuracy)

plt.scatter(x_train.iloc[:,0],x_train.iloc[:,1],c=y_train)
plt.xlabel("Passenger class")
plt.ylabel("Age")
plt.title("Training Set")
plt.show()

plt.scatter(x_test.iloc[:,0],x_test.iloc[:,1],c=y_test)
plt.xlabel("Passenger class")
plt.ylabel("Age")
plt.title("Test Set")
plt.show()